# Generated by Codex for the form validation showcase.

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_name", models.CharField(max_length=64)),
                (
                    "field_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("error_code", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["form_name", "field_name", "error_code"],
                name="forms_lab_v_form_na_8af264_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationlog",
            index=models.Index(
                fields=["created_at"], name="forms_lab_v_created_465afc_idx"
            ),
        ),
    ]
